# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Kisi2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Kisi2UTS(object):
    def setupUi(self, Kisi2UTS):
        Kisi2UTS.setObjectName("Kisi2UTS")
        Kisi2UTS.resize(528, 576)
        self.centralwidget = QtWidgets.QWidget(Kisi2UTS)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(150, 490, 341, 21))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(41, 31, 450, 451))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setStyleSheet("font: 75 13pt \"MS Shell Dlg 2\";\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.widget1)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.verticalLayout.addLayout(self.formLayout_4)
        Kisi2UTS.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Kisi2UTS)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 528, 26))
        self.menubar.setObjectName("menubar")
        Kisi2UTS.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Kisi2UTS)
        self.statusbar.setObjectName("statusbar")
        Kisi2UTS.setStatusBar(self.statusbar)

        self.retranslateUi(Kisi2UTS)
        QtCore.QMetaObject.connectSlotsByName(Kisi2UTS)

    def retranslateUi(self, Kisi2UTS):
        _translate = QtCore.QCoreApplication.translate
        Kisi2UTS.setWindowTitle(_translate("Kisi2UTS", "MainWindow"))
        self.pushButton.setText(_translate("Kisi2UTS", "TAMBAH"))
        self.pushButton_2.setText(_translate("Kisi2UTS", "EDIT"))
        self.pushButton_3.setText(_translate("Kisi2UTS", "CLEAR"))
        self.pushButton_4.setText(_translate("Kisi2UTS", "HAPUS"))
        self.label.setText(_translate("Kisi2UTS", "Data Mahasiswa"))
        self.label_2.setText(_translate("Kisi2UTS", "NIM"))
        self.label_3.setText(_translate("Kisi2UTS", "Nama"))
        self.label_4.setText(_translate("Kisi2UTS", "Jurusan"))
        self.label_5.setText(_translate("Kisi2UTS", "No.Telp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Kisi2UTS = QtWidgets.QMainWindow()
    ui = Ui_Kisi2UTS()
    ui.setupUi(Kisi2UTS)
    Kisi2UTS.show()
    sys.exit(app.exec_())
