# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
from PyQt5.QtWidgets import*
from datamhs import*


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.koneksi()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(729, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(4, -1, 721, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(0, -10, 711, 541))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("bg pink pastel.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(240, 80, 251, 41))
        self.label_2.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 190, 531, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.NIM = QtWidgets.QLabel(self.layoutWidget)
        self.NIM.setObjectName("NIM")
        self.gridLayout.addWidget(self.NIM, 0, 0, 1, 1)
        self.txtNim = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtNim.setObjectName("txtNim")
        self.gridLayout.addWidget(self.txtNim, 0, 1, 1, 1)
        self.Nama = QtWidgets.QLabel(self.layoutWidget)
        self.Nama.setObjectName("Nama")
        self.gridLayout.addWidget(self.Nama, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.Jurusan = QtWidgets.QLabel(self.layoutWidget)
        self.Jurusan.setObjectName("Jurusan")
        self.gridLayout.addWidget(self.Jurusan, 2, 0, 1, 1)
        self.txtJurusan = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtJurusan.setObjectName("txtJurusan")
        self.gridLayout.addWidget(self.txtJurusan, 2, 1, 1, 1)
        self.NoTelp = QtWidgets.QLabel(self.layoutWidget)
        self.NoTelp.setObjectName("NoTelp")
        self.gridLayout.addWidget(self.NoTelp, 3, 0, 1, 1)
        self.txtNo = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtNo.setObjectName("txtNo")
        self.gridLayout.addWidget(self.txtNo, 3, 1, 1, 1)
        self.btnSubmit_2 = QtWidgets.QPushButton(self.tab)
        self.btnSubmit_2.setGeometry(QtCore.QRect(540, 330, 93, 28))
        self.btnSubmit_2.setObjectName("btnSubmit_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(0, -10, 711, 541))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("R.jpg"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(250, 100, 251, 41))
        self.label_4.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.btnSubmit = QtWidgets.QPushButton(self.tab_2)
        self.btnSubmit.setGeometry(QtCore.QRect(520, 240, 93, 28))
        self.btnSubmit.setObjectName("btnSubmit")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(110, 170, 501, 53))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Username = QtWidgets.QLabel(self.layoutWidget1)
        self.Username.setObjectName("Username")
        self.gridLayout_2.addWidget(self.Username, 0, 0, 1, 1)
        self.txtNim_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txtNim_2.setObjectName("txtNim_2")
        self.gridLayout_2.addWidget(self.txtNim_2, 0, 1, 1, 1)
        self.Password = QtWidgets.QLabel(self.layoutWidget1)
        self.Password.setObjectName("Password")
        self.gridLayout_2.addWidget(self.Password, 1, 0, 1, 1)
        self.txtPass = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txtPass.setObjectName("txtPass")
        self.gridLayout_2.addWidget(self.txtPass, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 729, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.btnSubmit_2.clicked.connect(self.submit) 
        self.txtPass.setEchoMode(QtWidgets.QLineEdit.Password) 
        self.btnSubmit.clicked.connect(self.login) 
        self.btnSubmit_2.clicked.connect(self.submit) 

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "From Mahasiswa"))
        self.NIM.setText(_translate("MainWindow", "NIM"))
        self.Nama.setText(_translate("MainWindow", "Nama"))
        self.Jurusan.setText(_translate("MainWindow", "Jurusan"))
        self.NoTelp.setText(_translate("MainWindow", "No.Telp"))
        self.btnSubmit_2.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Form"))
        self.label_4.setText(_translate("MainWindow", "Login Admin"))
        self.btnSubmit.setText(_translate("MainWindow", "LOGIN"))
        self.Username.setText(_translate("MainWindow", "Username"))
        self.Password.setText(_translate("MainWindow", "Password"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Admin"))

    #Fungsi untukk mengkoneksikan ke database
    def koneksi(self):
        con = pymysql.connect(db='db_mhs', user='root', passwd='', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        if(cur):
            self.messagebox("Koneksi","Koneksi Berhasil")
        else:
            self.messagebox("Koneksi", "Koneksi gagal")

    #fungsi untuk memunculkan messagebox
    def messagebox(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec()

    #fungsi untuk memasukan data ke database
    def submit(self): 
        nim = self.txtNim.text() 
        nama = self.lineEdit_2.text() 
        jurusan = self.txtJurusan.text() 
        no = self.txtNo.text() 
        insert = (nim, nama, jurusan, no) 
        print(insert) 
        if self.lineEdit_2.text() and self.lineEdit_2.text() and self.txtJurusan.text() and self.txtNo.text(): 
            con = pymysql.connect(db='db_mhs', user='root', passwd='', host='localhost', port=3306, autocommit=True) 
            cur = con.cursor() 
            sql = "INSERT INTO mhs(nim, nama, jurusan, no)" + "VALUES"+ str(insert) 
            data = cur.execute(sql) 
            self.messagebox("SUKSES", "Data Berhasil di Submit") 
        else: 
            self.messagebox("GAGAL", "Mohon lengkapi form ") 

    #fungsi untuk login
    def login(self): 
        uname = self.txtNim_2.text() 
        pw = self.txtPass.text() 
        con = pymysql.connect(db='db_mhs', user='root', passwd='', host='localhost', port=3306, autocommit=True) 
        cur = con.cursor() 
        sql = "SELECT * from admin where uname=%s and pw=%s" 
        data = cur.execute(sql, (uname, pw)) 
        if(len(cur.fetchall())>0): 
            self.form = datamhs() 
            self.form.show() 
        else: 
            self.messagebox("GAGAL", "Username atau Password Salah ! ") 
    
    def openadmin(self):
        self.form = datamhs()
        self.form.show()

    #fungsi untuk menghapus lineedit setelah memasukan data
    def clear(self):
        self.txtNim.clear()
        self.txtNim.setEnabled(True)
        self.lineEdit_2.clear()
        self.txtJurusan.clear()
        self.txtNo.clear()

    def clearlogin(self):
        self.txtNim_2.clear()
        self.txtPass.clear()

class datamhs(QWidget):
    def __init__ (self):
        super().__init__()
        self.datamhs = Ui_MainWindow()
        self.datamhs.setupUi(self)
        self.show()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
