# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'styles.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Styles(object):
    def setupUi(self, Styles):
        Styles.setObjectName("Styles")
        Styles.resize(582, 510)
        self.centralwidget = QtWidgets.QWidget(Styles)
        self.centralwidget.setObjectName("centralwidget")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 20, 41, 21))
        self.label_9.setObjectName("label_9")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(60, 20, 141, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(230, 20, 91, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(330, 20, 121, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(460, 20, 121, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 50, 51, 16))
        self.label_10.setObjectName("label_10")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 70, 271, 141))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(20, 10, 71, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 40, 61, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 70, 51, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 100, 81, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 220, 271, 201))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(-5, 1, 271, 171))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(300, 50, 51, 16))
        self.label_11.setObjectName("label_11")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(300, 70, 271, 141))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 251, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 40, 251, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(12, 70, 251, 28))
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(299, 239, 271, 181))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 251, 22))
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setGeometry(QtCore.QRect(10, 40, 251, 22))
        self.spinBox.setObjectName("spinBox")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_3)
        self.dateTimeEdit.setGeometry(QtCore.QRect(10, 70, 251, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 110, 181, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.groupBox_3)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(10, 150, 181, 16))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.dial = QtWidgets.QDial(self.groupBox_3)
        self.dial.setGeometry(QtCore.QRect(210, 100, 50, 64))
        self.dial.setObjectName("dial")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(300, 220, 81, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 430, 551, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        Styles.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Styles)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 26))
        self.menubar.setObjectName("menubar")
        Styles.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Styles)
        self.statusbar.setObjectName("statusbar")
        Styles.setStatusBar(self.statusbar)

        self.retranslateUi(Styles)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Styles)

    def retranslateUi(self, Styles):
        _translate = QtCore.QCoreApplication.translate
        Styles.setWindowTitle(_translate("Styles", "MainWindow"))
        self.label_9.setText(_translate("Styles", "Style:"))
        self.comboBox_6.setItemText(0, _translate("Styles", "Fusion"))
        self.checkBox.setText(_translate("Styles", "Use style\'s"))
        self.checkBox_2.setText(_translate("Styles", "Standard palette"))
        self.checkBox_3.setText(_translate("Styles", "Disable widgets"))
        self.label_10.setText(_translate("Styles", "Group 1"))
        self.radioButton.setText(_translate("Styles", "Python"))
        self.radioButton_2.setText(_translate("Styles", "Ruby"))
        self.radioButton_3.setText(_translate("Styles", "PHP"))
        self.checkBox_4.setText(_translate("Styles", "Tri-state"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Styles", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Styles", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Styles", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Styles", "4"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Styles", "1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Styles", "2"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Styles", "3"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Styles", "4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Styles", "List"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Styles", "Text Edit"))
        self.label_11.setText(_translate("Styles", "Group 2"))
        self.pushButton.setText(_translate("Styles", "Default Push Button"))
        self.pushButton_2.setText(_translate("Styles", "Toggle Push Button"))
        self.pushButton_3.setText(_translate("Styles", "Flat Push Button"))
        self.checkBox_5.setText(_translate("Styles", "Group 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Styles = QtWidgets.QMainWindow()
    ui = Ui_Styles()
    ui.setupUi(Styles)
    Styles.show()
    sys.exit(app.exec_())

