# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calender.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Calender(object):
    def setupUi(self, Calender):
        Calender.setObjectName("Calender")
        Calender.resize(973, 587)
        Calender.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(Calender)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 431, 291))
        self.groupBox.setObjectName("groupBox")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBox)
        self.calendarWidget.setGeometry(QtCore.QRect(20, 30, 391, 241))
        self.calendarWidget.setObjectName("calendarWidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 310, 431, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 30, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 101, 16))
        self.label_3.setObjectName("label_3")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox_2)
        self.dateEdit_2.setGeometry(QtCore.QRect(179, 60, 231, 22))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.dateEdit_3 = QtWidgets.QDateEdit(self.groupBox_2)
        self.dateEdit_3.setGeometry(QtCore.QRect(180, 90, 231, 22))
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox_2)
        self.dateEdit.setGeometry(QtCore.QRect(180, 30, 231, 22))
        self.dateEdit.setWrapping(False)
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setTimeSpec(QtCore.Qt.TimeZone)
        self.dateEdit.setObjectName("dateEdit")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(450, 10, 501, 291))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(20, 110, 101, 16))
        self.label_6.setObjectName("label_6")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(150, 30, 331, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_2.setGeometry(QtCore.QRect(150, 70, 331, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_3.setGeometry(QtCore.QRect(150, 110, 331, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setGeometry(QtCore.QRect(20, 150, 81, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_2.setGeometry(QtCore.QRect(400, 150, 81, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_4.setGeometry(QtCore.QRect(150, 190, 331, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 190, 111, 16))
        self.label_7.setObjectName("label_7")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_5.setGeometry(QtCore.QRect(150, 230, 331, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(20, 230, 101, 16))
        self.label_8.setObjectName("label_8")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(450, 310, 501, 151))
        self.groupBox_4.setObjectName("groupBox_4")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_6.setGeometry(QtCore.QRect(240, 30, 241, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(20, 30, 101, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(20, 60, 101, 16))
        self.label_10.setObjectName("label_10")
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_7.setGeometry(QtCore.QRect(240, 60, 241, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(20, 90, 101, 16))
        self.label_11.setObjectName("label_11")
        self.comboBox_8 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_8.setGeometry(QtCore.QRect(240, 90, 241, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_3.setGeometry(QtCore.QRect(380, 120, 101, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 120, 141, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        Calender.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Calender)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 973, 26))
        self.menubar.setObjectName("menubar")
        Calender.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Calender)
        self.statusbar.setObjectName("statusbar")
        Calender.setStatusBar(self.statusbar)

        self.retranslateUi(Calender)
        QtCore.QMetaObject.connectSlotsByName(Calender)

    def retranslateUi(self, Calender):
        _translate = QtCore.QCoreApplication.translate
        Calender.setWindowTitle(_translate("Calender", "MainWindow"))
        self.groupBox.setTitle(_translate("Calender", "Preview"))
        self.groupBox_2.setTitle(_translate("Calender", "Dates"))
        self.label.setText(_translate("Calender", "Minimum Date:"))
        self.label_2.setText(_translate("Calender", "Current Date:"))
        self.label_3.setText(_translate("Calender", "Maximum Date:"))
        self.groupBox_3.setTitle(_translate("Calender", "General Options"))
        self.label_4.setText(_translate("Calender", "Locale:"))
        self.label_5.setText(_translate("Calender", "Week starts on:"))
        self.label_6.setText(_translate("Calender", "Selection mode:"))
        self.comboBox.setItemText(0, _translate("Calender", "German/Germany"))
        self.comboBox.setItemText(1, _translate("Calender", "Jepang/Japan"))
        self.comboBox.setItemText(2, _translate("Calender", "Indonesia/Indonesia"))
        self.comboBox_2.setItemText(0, _translate("Calender", "Sunday"))
        self.comboBox_2.setItemText(1, _translate("Calender", "Monday"))
        self.comboBox_2.setItemText(2, _translate("Calender", "Tuesday"))
        self.comboBox_2.setItemText(3, _translate("Calender", "Wednesday"))
        self.comboBox_2.setItemText(4, _translate("Calender", "Thursday"))
        self.comboBox_2.setItemText(5, _translate("Calender", "Friday"))
        self.comboBox_2.setItemText(6, _translate("Calender", "Saturday"))
        self.comboBox_3.setItemText(0, _translate("Calender", "Single Selection"))
        self.checkBox.setText(_translate("Calender", "Grid"))
        self.checkBox_2.setText(_translate("Calender", "Navigation bar"))
        self.comboBox_4.setItemText(0, _translate("Calender", "Short day names"))
        self.label_7.setText(_translate("Calender", "Horizontal header:"))
        self.comboBox_5.setItemText(0, _translate("Calender", "ISO week numbers"))
        self.label_8.setText(_translate("Calender", "Vertical header:"))
        self.groupBox_4.setTitle(_translate("Calender", "Text Formats"))
        self.comboBox_6.setItemText(0, _translate("Calender", "Black"))
        self.comboBox_6.setItemText(1, _translate("Calender", "Red"))
        self.comboBox_6.setItemText(2, _translate("Calender", "Green"))
        self.label_9.setText(_translate("Calender", "Weekday color:"))
        self.label_10.setText(_translate("Calender", "Weekend color:"))
        self.comboBox_7.setItemText(0, _translate("Calender", "Red"))
        self.comboBox_7.setItemText(1, _translate("Calender", "Black"))
        self.comboBox_7.setItemText(2, _translate("Calender", "Green"))
        self.label_11.setText(_translate("Calender", "Header text:"))
        self.comboBox_8.setItemText(0, _translate("Calender", "Bold"))
        self.checkBox_3.setText(_translate("Calender", "May 1 in red"))
        self.checkBox_4.setText(_translate("Calender", "First Friday in blue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calender = QtWidgets.QMainWindow()
    ui = Ui_Calender()
    ui.setupUi(Calender)
    Calender.show()
    sys.exit(app.exec_())

